name: Automatisation des tests

on:
  push:

jobs:
  # -----------------------
  # Compilation
  # -----------------------
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compilation et tests
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          make test

  # -----------------------
  # Test add
  # -----------------------
  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction add
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator add 2 3

  # -----------------------
  # Test sub
  # -----------------------
  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction sub
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator sub 3 -2

  # -----------------------
  # Test mul
  # -----------------------
  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction mul
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator mul 5 5

  # -----------------------
  # Test div
  # -----------------------
  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction div
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator div 1 5

  # -----------------------
  # Test car
  # -----------------------
  Test_Car:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction car
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator car 5

  # -----------------------
  # Déploiement
  # -----------------------
  Deploy:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Car]
    steps:
      - name: Déploiement
        run: echo "Déploiement de la solution"
