name: Automatisation des tests

on:
  push:

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compilation et tests
        run: |
          cmake -S . -B build
          cmake --build build
          ctest --output-on-failure

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction add
        run: |
          ./build/calculator add 2 3

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction sub
        run: |
          ./build/calculator sub 3 -2

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction mul
        run: |
          ./build/calculator mul 5 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction div
        run: |
          ./build/calculator div 1 5

  Test_Car:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction car
        run: |
          ./build/calculator car 5

  Deploy:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Car]
    steps:
      - name: Déploiement
        run: echo "Déploiement de la solution"
