name: Automatisation des tests

on:
  push:

jobs:
  # -----------------------
  # Compilation principale
  # -----------------------
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compilation et tests
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          make test

  # -----------------------
  # Test add
  # -----------------------
  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run test "add"
        run: |
          cd build
          ./src/calculator add 10 5

  # -----------------------
  # Test sub
  # -----------------------
  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run test "sub"
        run: |
          cd build
          ./src/calculator sub 3 -2

  # -----------------------
  # Test mul
  # -----------------------
  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run test "mul"
        run: |
          cd build
          ./src/calculator mul 5 5

  # -----------------------
  # Test div
  # -----------------------
  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run test "div"
        run: |
          cd build
          ./src/calculator div 1 5

  # -----------------------
  # Test car
  # -----------------------
  Test_Car:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run test "car"
        run: |
          cd build
          ./src/calculator car 5

  # -----------------------
  # Déploiement
  # -----------------------
  Deploy:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Car]
    steps:
      - name: Déploiement final
        run: |
          echo "Déploiement de la solution"
