name: Automatisation des tests

on:
  push:

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compilation et tests
        run: |
          mkdir -p build
          cd build
          cmake $GITHUB_WORKSPACE
          make
          make test

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction add
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./calculator add 2 3

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction sub
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./calculator sub 3 -2

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction mul
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./calculator mul 5 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction div
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./calculator div 1 5

  Test_Car:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction car
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./calculator car 5

  Deploy:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Car]
    steps:
      - name: Déploiement
        run: echo "Déploiement de la solution"
